CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(20) UNIQUE NOT NULL,
  pass VARCHAR(20),
  auth VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS task (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(20) UNIQUE NOT NULL,
  type VARCHAR(20) NOT NULL,
  task_name VARCHAR(30) NOT NULL,
  task_description VARCHAR(300),
  priority VARCHAR(10) NOT NULL,
  deadline DATE NOT NULL,
  is_completed TINYINT NOT NULL
);